apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/generated-namespace: "true"
    maas.opendatahub.io/gateway-access: "true"
    evalhub.trustyai.opendatahub.io/tenant: "true"
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen3-06b
  namespace: llm
  annotations:
    openshift.io/display-name: "Qwen/Qwen3-0.6B"
    opendatahub.io/model-type: generative
    security.opendatahub.io/enable-auth: "true"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
spec:
  replicas: 1
  model:
    name: qwen3-06b
    uri: hf://Qwen/Qwen3-0.6B
  router:
    scheduler: {}
    route: {}
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
  template:
    containers:
      - name: main
        image: registry.redhat.io/rhaii-early-access/vllm-cpu-rhel9:3.5.0-ea.2
        command:
          - python
          - -m
          - vllm.entrypoints.openai.api_server
        args:
          - "--served-model-name={{.Name}}"
          - --model=/mnt/models
          - --max-model-len=2048
          - --enable-ssl-refresh
          - --ssl-certfile=/var/run/kserve/tls/tls.crt
          - --ssl-keyfile=/var/run/kserve/tls/tls.key
          - --enable-force-include-usage
        env:
          - name: HF_HOME
            value: /tmp/hf_home
          - name: HF_HUB_DISABLE_XET
            value: "1"
          - name: VLLM_CPU_KVCACHE_SPACE
            value: "4"
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 8Gi
          limits:
            cpu: "2"
            memory: 8Gi
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: qwen3-06b
  namespace: llm
spec:
  modelRef:
    kind: LLMInferenceService
    name: qwen3-06b
