apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: gpt-oss-20b
  namespace: llm
  annotations:
    openshift.io/display-name: "openai/gpt-oss-20b"
    opendatahub.io/model-type: generative
    security.opendatahub.io/enable-auth: "true"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
spec:
  replicas: 1
  model:
    name: gpt-oss-20b
    uri: hf://openai/gpt-oss-20b
  router:
    scheduler: {}
    route: {}
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
  template:
    containers:
      - name: main
        image: registry.redhat.io/rhaii-early-access/vllm-cuda-rhel9:3.5.0-ea.2
        command:
          - python
          - -m
          - vllm.entrypoints.openai.api_server
        args:
          - "--served-model-name={{.Name}}"
          - --model=/mnt/models
          - --max-model-len=8192
          - --enable-ssl-refresh
          - --ssl-certfile=/var/run/kserve/tls/tls.crt
          - --ssl-keyfile=/var/run/kserve/tls/tls.key
          - --enable-force-include-usage
          - --enable-auto-tool-choice
          - --tool-call-parser=openai
        env:
          - name: HF_HOME
            value: /tmp/hf_home
          - name: HF_HUB_DISABLE_XET
            value: "1"
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: "4"
            memory: 32Gi
            nvidia.com/gpu: "1"
          limits:
            cpu: "8"
            memory: 64Gi
            nvidia.com/gpu: "1"
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-L4
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gpt-oss-20b
  namespace: llm
spec:
  modelRef:
    kind: LLMInferenceService
    name: gpt-oss-20b
